name: Build and Release WinForms App (.NET 8)

on:
  push:
    tags:
      - 'v*'   # v1.0 gibi bir tag push edince çalışır (örnek: v1.0, v1.1 vs.)
  workflow_dispatch: # manuel çalıştırma için

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true /p:WindowsAppSDKSelfContained=true /p:EnableWindowsTargeting=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrowserApp
          path: |
            **/bin/Release/**/publish/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/bin/Release/**/publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
